apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - externalsecret.yaml
  - issuer.yaml
  - certificate.yaml
  - keycloak
  - obc.yaml
commonLabels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
images:
  - name: backstage-showcase
    newName: quay.io/rhsummit23backstage/backstage-showcase
